### PR TITLE
Don't auto increment when value is provided

### PR DESCRIPTION
**Pull request by fedegl**
It's helpful in situations where you are migrating data from a relational database and need to keep the current id's of any record.

### CODE REVIEW

**Comment by jffjs** [comment]
Hey, thanks for your input!  I'll merge this and update the gem soon.

**Comment by fedegl** [comment]
Great! Thanks for the merging it back so fast!

**Comment by fedegl** [comment]
I would appreciate it if you could release a new version to rubygems. Thanks!

**Comment by jffjs** [comment]
Hey, sorry for the delay!  I just updated the gem to 0.0.6.

**Pull request merged**
